### ISSUE TITLE
unknown instruction

### ISSUE THREAD

**Issue by zzugyl** [skonb/OpenH264Recorder#1]
E:\code\OpenH264Recorder\app\src\main\cpp\libyuv\source\row_dspr2.cc
Error:(224, 8) error: unknown instruction
ndk配置了，版本14

**Comment by shukob** [comment]
Thank you for reporting this.

Sorry, I do not have MIPS devices and tested for it.
Would you please check with the latest libyuv from google repository?(https://chromium.googlesource.com/libyuv/libyuv/)

Thanks,
Shunpei

**Comment by zzugyl** [comment]
I will try.

**Comment by zzugyl** [comment]
compile success with latest libyuv
but Run app get error：
`rocess: me.skonb.openh264cameraview, PID: 23703
                                                   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{me.skonb.openh264cameraview/me.skonb.openh264cameraview.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "me.skonb.openh264cameraview.MainActivity" on path: DexPathList[[zip file "/data/app/me.skonb.openh264cameraview-1/base.apk"],nativeLibraryDirectories=[/data/app/me.skonb.openh264cameraview-1/lib/arm64, /data/app/me.skonb.openh264cameraview-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
`

**Comment by shukob** [comment]
Seems like build configuration problem. Did you change something in gradle related things?
Also, try to rebuild the project and re-run.

**Comment by zzugyl** [comment]
I change some word in english word,fixed it.
but still have bugs in my devices 
` at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                              Caused by: java.io.IOException: No such file or directory
                                                                                 at java.io.UnixFileSystem.createFileExclusively0(Native Method)
                                                                                 at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
                                                                                 at java.io.File.createNewFile(File.java:948)
                                                                                 at me.skonb.openh264cameraview.MP4Recorder.ensureOutputFiles(MP4Recorder.kt:54)`
file is already maked successful

**Comment by shukob** [comment]
I think the code itself is safe, but if exceptions are thrown, would you try to 'try catch' createNewFile-s?
